/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "app.h"

std::string chotc::chot_app::apply(char *args) {
    return std::string(args);
}
