/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef APP_H
#define APP_H

#include <string>

namespace chotc
{
    class chot_app
    {
    public:
        std::string apply(char *args);
    };
}

#endif
